// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUzYV3xdwRUr4Mh_32cybI5o2kxT1elc8',
    appId: '1:672166011550:web:a15d1821daaff8da97d18f',
    messagingSenderId: '672166011550',
    projectId: 'subtrack-39e2b',
    authDomain: 'subtrack-39e2b.firebaseapp.com',
    storageBucket: 'subtrack-39e2b.firebasestorage.app',
    measurementId: 'G-C1P0DB95KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWudEc0wy3Fa0GVhIidW0OgBXZA3rTs1Q',
    appId: '1:672166011550:android:3c8b7429d7c6199a97d18f',
    messagingSenderId: '672166011550',
    projectId: 'subtrack-39e2b',
    storageBucket: 'subtrack-39e2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk--bwEYsroB-BZlpq96QyumMG3aCdcoA',
    appId: '1:672166011550:ios:81cee8b85112eb8f97d18f',
    messagingSenderId: '672166011550',
    projectId: 'subtrack-39e2b',
    storageBucket: 'subtrack-39e2b.firebasestorage.app',
    iosBundleId: 'com.example.subtrackPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk--bwEYsroB-BZlpq96QyumMG3aCdcoA',
    appId: '1:672166011550:ios:81cee8b85112eb8f97d18f',
    messagingSenderId: '672166011550',
    projectId: 'subtrack-39e2b',
    storageBucket: 'subtrack-39e2b.firebasestorage.app',
    iosBundleId: 'com.example.subtrackPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUzYV3xdwRUr4Mh_32cybI5o2kxT1elc8',
    appId: '1:672166011550:web:2c64b10419ac5a6297d18f',
    messagingSenderId: '672166011550',
    projectId: 'subtrack-39e2b',
    authDomain: 'subtrack-39e2b.firebaseapp.com',
    storageBucket: 'subtrack-39e2b.firebasestorage.app',
    measurementId: 'G-PYV3F2S1Y9',
  );
}
